kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kong-operator
subjects:
- kind: ServiceAccount
  name: kong-operator
  namespace: kong
roleRef:
  kind: ClusterRole
  name: kong-operator
  apiGroup: rbac.authorization.k8s.io
